# List of worlds to load onEnable()
Worlds: []
# List of players to give the handicap TP star
HandicapTP: []
# List of players to keep armor on death
HandicapArmor: []
# List of custom recipes to enable/disable
Custom Recipes:
  Primed Pickaxe: true
  Strengthened Sword: true
  Bolstered Bow: true
  Trident: true
  Compact Anvil: true
  Bundled Arrows: true
  Golden Head: true
  Loyalty Book: true
  Trial Chambers Map: true